### ISSUE TITLE
ModuleNotFoundError: No module named 'notionscripts'

### ISSUE THREAD

**Issue by Klaudioz** [kevinjalbert/alfred-notion#8]
I got the following error after run any command with alfred:

[11:28:32.016] ERROR: Notion[Run Script] Traceback (most recent call last):
  File "/Users/172100/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EF87D811-021C-45B9-A871-CE8263AE312E/src/add_note.py", line 6, in <module>
    from notion_api import notion_api
  File "/Users/172100/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EF87D811-021C-45B9-A871-CE8263AE312E/src/notion_api.py", line 1, in <module>
    from notionscripts.notion_api import NotionApi
ModuleNotFoundError: No module named 'notionscripts'

I checked all the files are in the folder and when I did: `pip3 install -r requirements.txt
` I got:

> Requirement already satisfied: cachetools==3.1.0 in /usr/local/anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.1.0)
> Requirement already satisfied: notion==0.0.21 in /usr/local/anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.0.21)
> Requirement already satisfied: flake8==3.7.7 in /usr/local/anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (3.7.7)
> Requirement already satisfied: notion-scripts from git+git://github.com/kevinjalbert/notion-scripts@v0.2.0#egg=notion-scripts in /usr/local/anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.1.0)
> Requirement already satisfied: commonmark in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (0.9.0)
> Requirement already satisfied: requests in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (2.21.0)
> Requirement already satisfied: dictdiffer in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (0.8.0)
> Requirement already satisfied: tzlocal in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (2.0.0)
> Requirement already satisfied: cached-property in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (1.5.1)
> Requirement already satisfied: python-slugify in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (3.0.4)
> Requirement already satisfied: bs4 in /usr/local/anaconda3/lib/python3.7/site-packages (from notion==0.0.21->-r requirements.txt (line 2)) (0.0.1)
> Requirement already satisfied: entrypoints<0.4.0,>=0.3.0 in /usr/local/anaconda3/lib/python3.7/site-packages (from flake8==3.7.7->-r requirements.txt (line 3)) (0.3)
> Requirement already satisfied: pyflakes<2.2.0,>=2.1.0 in /usr/local/anaconda3/lib/python3.7/site-packages (from flake8==3.7.7->-r requirements.txt (line 3)) (2.1.1)
> Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /usr/local/anaconda3/lib/python3.7/site-packages (from flake8==3.7.7->-r requirements.txt (line 3)) (0.6.1)
> Requirement already satisfied: pycodestyle<2.6.0,>=2.5.0 in /usr/local/anaconda3/lib/python3.7/site-packages (from flake8==3.7.7->-r requirements.txt (line 3)) (2.5.0)
> Requirement already satisfied: future in /usr/local/anaconda3/lib/python3.7/site-packages (from commonmark->notion==0.0.21->-r requirements.txt (line 2)) (0.17.1)
> Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/anaconda3/lib/python3.7/site-packages (from requests->notion==0.0.21->-r requirements.txt (line 2)) (2.8)
> Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/anaconda3/lib/python3.7/site-packages (from requests->notion==0.0.21->-r requirements.txt (line 2)) (1.24.1)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/anaconda3/lib/python3.7/site-packages (from requests->notion==0.0.21->-r requirements.txt (line 2)) (3.0.4)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/anaconda3/lib/python3.7/site-packages (from requests->notion==0.0.21->-r requirements.txt (line 2)) (2019.3.9)
> Requirement already satisfied: pytz in /usr/local/anaconda3/lib/python3.7/site-packages (from tzlocal->notion==0.0.21->-r requirements.txt (line 2)) (2018.9)
> Requirement already satisfied: text-unidecode>=1.3 in /usr/local/anaconda3/lib/python3.7/site-packages (from python-slugify->notion==0.0.21->-r requirements.txt (line 2)) (1.3)
> Requirement already satisfied: beautifulsoup4 in /usr/local/anaconda3/lib/python3.7/site-packages (from bs4->notion==0.0.21->-r requirements.txt (line 2)) (4.7.1)
> Requirement already satisfied: soupsieve>=1.2 in /usr/local/anaconda3/lib/python3.7/site-packages (from beautifulsoup4->bs4->notion==0.0.21->-r requirements.txt (line 2)) (1.8)

```
python --version
Python 3.7.3

```

**Comment by kevinjalbert** [comment]
Looking at the information presented it appears that `notion-scripts` is installed correctly. Can you verify it is there:

```
❯ python3                                                                                                                                                                    Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from notionscripts.notion_api import NotionApi
>>> NotionApi()
<notionscripts.notion_api.NotionApi object at 0x10e779748>
```

All the scripts are expecting to use `python3`.

-----

Something else you could try is executing one of the inner scripts directly:

```
❯ python3 src/get_current_day.py                                                                                                                                            
id='1efe0646-0729-4817-8427-0aa2922b9642'
notion://www.notion.so/126a1f0e43534098b9d8f218f9979390
```

-----

I wonder if its just something in the Alfred environment that is causing issues.

**Comment by Klaudioz** [comment]
> Thanks for your answer. For the first one I got:

```
python3
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from notionscripts.notion_api import NotionApi
>>> NotionApi()
<notionscripts.notion_api.NotionApi object at 0x106bf7cc0>

```

For the 2nd one I got this error:

```
python3 get_current_day.py
Traceback (most recent call last):
  File "get_current_day.py", line 10, in <module>
    print(app_url(notion_api.current_day().get_browseable_url()))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/notionscripts/notion_api.py", line 66, in current_day
    days_page = self.current_week().children[1].children[1]
  File "/usr/local/anaconda3/lib/python3.7/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/notionscripts/notion_api.py", line 51, in current_week
    if week_page.title.startswith("Week " + week_number):
AttributeError: 'DividerBlock' object has no attribute 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_current_day.py", line 13, in <module>
    sys.stderr.write(e)
TypeError: write() argument must be str, not AttributeError

```

**Comment by kevinjalbert** [comment]
>  File "/usr/local/anaconda3/lib/python3.7/site-packages/notionscripts/notion_api.py", line 51, in current_week
    if week_page.title.startswith("Week " + week_number):
AttributeError: 'DividerBlock' object has no attribute 'title'

So this suggests that it is failing when trying to get the `title` from a `week_page`. It seems like the template has changed ever so slightly. This workflow is heavily dependant on the template being set correctly as the structure of the Notion blocks is really important.

This sounds like a similar issue to what was found in #6 (where the template was modified slightly). I would recommend looking at what might have changed. Or debugging slightly like that one issue explained.

**Comment by kevinjalbert** [comment]
@Klaudioz I'm closing due to inactivity. We can reopen this again if needed.

**Comment by sundevilyang** [comment]
@kevinjalbert hey kevin, I got the following error when run `python3 src/get_current_day.py`

```
python src/get_current_day.py
Traceback (most recent call last):
  File "src/get_current_day.py", line 10, in <module>
    print(app_url(notion_api.current_day().get_browseable_url()))
  File "/Users/ywen8/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/Users/ywen8/.pyenv/versions/3.8.1/lib/python3.8/site-packages/notionscripts/notion_api.py", line 63, in current_day
    days_page = self.current_week().children[1].children[1]
AttributeError: 'NoneType' object has no attribute 'children'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/get_current_day.py", line 13, in <module>
    sys.stderr.write(e)
TypeError: write() argument must be str, not AttributeError
```
